# Generated by Django 5.1.8 on 2025-06-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='autori_eliminati',
            field=models.TextField(blank=True, help_text='Nomi degli autori eliminati, separati da virgola'),
        ),
    ]
