# Generated by Django 5.2.1 on 2025-07-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0002_articolo_autori_eliminati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='articoli/'),
        ),
    ]
