# Generated by Django 5.1.8 on 2025-06-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('date_evento', models.JSONField(default=list)),
                ('luogo', models.CharField(max_length=255)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='immagini_eventi/')),
                ('numero_partecipanti', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('stato', models.CharField(choices=[('IN_ATTESA', 'IN_ATTESA'), ('CONCLUSO', 'CONCLUSO'), ('AL_COMPLETO', 'AL_COMPLETO'), ('ANNULLATO', 'ANNULLATO')], default='IN_ATTESA', max_length=50)),
                ('iscritti', models.ManyToManyField(blank=True, db_table='evento_iscritti', related_name='eventi_iscritti', to='accounts.profiloutente')),
                ('organizzatore', models.ForeignKey(blank=True, db_column='organizzatore_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi_organizzati', to='accounts.profiloutente')),
            ],
            options={
                'db_table': 'eventi',
                'ordering': [models.OrderBy(models.F('date_evento'), descending=True)],
            },
        ),
    ]
