# Generated by Django 5.2.1 on 2025-07-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='posti_massimi',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
