# Generated by Django 5.2.1 on 2025-07-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0002_evento_posti_massimi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-inizio_evento']},
        ),
        migrations.RemoveField(
            model_name='evento',
            name='date_evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='fine_evento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='inizio_evento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
