# Generated by Django 5.2.1 on 2025-07-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0003_alter_evento_options_remove_evento_date_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='eventi/'),
        ),
    ]
