# Generated by Django 5.1.8 on 2025-06-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tessera', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('immagine_profilo', models.ImageField(blank=True, null=True, upload_to='immagini_di_profilo/')),
                ('data_tesseramento', models.DateField()),
            ],
            options={
                'db_table': 'utenti',
            },
        ),
    ]
