# Generated by Django 5.1.8 on 2025-06-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiloutente',
            name='email',
        ),
    ]
