# Generated by Django 5.1.8 on 2025-06-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiloutente',
            name='password',
        ),
        migrations.AlterField(
            model_name='profiloutente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profiloutente',
            name='numero_tessera',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
