# Generated by Django 5.2.1 on 2025-07-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profiloutente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiloutente',
            name='immagine_profilo',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/foto_profilo/'),
        ),
    ]
