# Generated by Django 5.1.8 on 2025-06-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profiloutente_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiloutente',
            name='data_tesseramento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
